# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a11f6a6d34ad01a7024323af769195f1194e2b127b917aa17ea99614694f1afc2ddfa685d518f1bd072e94097f557fa6b3d4de4138fc1622d848fe852227211

test:
  secret_key_base: 87bfa43698bb0c5b2c1f346eb0f37a4a641550ff16be428a798a09ec961acfd11425f01e9f341d0e58d9a91b3c27ea784969f95104a82d3b1215257c1b2162b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
